"""
Standard Re-Verification Report Template v1.0 Definition.
Reference: 'BACKGROUND INFORMATION/RE-VERIFICATION REPORT FORMAT'
Implements deterministic, versioned template hierarchy with stable row IDs.
"""
from app.report_templates.schema import (
    ReportTemplate,
    HeaderConfig,
    HeaderField,
    ParticularItem,
    FooterConfig,
    FooterSignatoryBlock,
    EvidenceCategory,
)

HEADER_CONFIG = HeaderConfig(
    organization_name="SMARTVERIFY / RETAIL LENDING RE-VERIFICATION",
    report_title="BACKGROUND INFORMATION/RE-VERIFICATION REPORT FORMAT",
    report_subtitle="Pre-Sanction Background Investigation & Document Re-Verification Dossier",
    fields=[
        HeaderField(key="organization_name", label="Organization / Client Name", required=True),
        HeaderField(key="report_title", label="Report Title", required=True),
        HeaderField(key="application_no", label="Application No.", required=True),
        HeaderField(key="borrower_name", label="Borrower Name", required=True),
        HeaderField(key="loan_type", label="Loan Type", required=True),
        HeaderField(key="loan_amount", label="Loan Amount", required=True),
        HeaderField(key="branch", label="Branch", required=True),
        HeaderField(key="report_date", label="Report Date", required=True),
    ],
)

FOOTER_CONFIG = FooterConfig(
    signatories=[
        FooterSignatoryBlock(
            key="authorized_signatory",
            role="Verification Field Officer",
            title="Authorized Signatory / Investigating Official",
            requires_date=True,
            requires_remarks=False,
        ),
        FooterSignatoryBlock(
            key="branch_head_scrutiny",
            role="Branch Manager / Head",
            title="Branch Use / Branch Head Scrutiny & Acceptance",
            requires_date=True,
            requires_remarks=True,
        ),
        FooterSignatoryBlock(
            key="report_prepared_by",
            role="System / Preparing Official",
            title="Report Generated & Compiled By",
            requires_date=True,
            requires_remarks=False,
        ),
    ],
    confidentiality_notice="Confidential Banking Document - Strictly for Internal Credit Assessment & Re-Verification Use Only",
)

EVIDENCE_CATEGORIES = [
    EvidenceCategory(
        key="applicant_kyc",
        title="Applicant Officially Valid KYC Documents",
        description="Aadhaar, PAN, Driving Licence, Passport, or Voter ID copies of the primary applicant",
        required=True,
    ),
    EvidenceCategory(
        key="guarantor_kyc",
        title="Guarantor / Co-Applicant KYC Documents",
        description="Officially valid KYC identity proofs of co-applicants and guarantors",
        required=False,
    ),
    EvidenceCategory(
        key="government_verification",
        title="Government Portal Verification Screenshots",
        description="UIDAI Aadhaar validity and Income Tax e-Filing PAN-Aadhaar linking confirmation portal screenshots",
        required=True,
    ),
    EvidenceCategory(
        key="income_documents",
        title="Income Proof & Substantiation Documents",
        description="Salary slips, Form 16, ITR acknowledgment forms, audited balance sheets, or income certificates",
        required=True,
    ),
    EvidenceCategory(
        key="bank_documents",
        title="Bank Statements & Financial Records",
        description="Bank account statements covering examined period, bank passbooks, or e-statements",
        required=True,
    ),
    EvidenceCategory(
        key="residence_evidence",
        title="Residence Physical Visit & Site Inspection Evidence",
        description="Geotagged physical residence visit photographs, site building view, and locality landmarks",
        required=True,
    ),
    EvidenceCategory(
        key="vehicle_invoice",
        title="Vehicle / Machinery Proforma Invoice & Receipts",
        description="Manufacturer/dealer quotation, proforma invoice, and advance margin money payment receipts",
        required=False,
    ),
    EvidenceCategory(
        key="dealer_evidence",
        title="Dealer / Sub-Dealer Verification Evidence",
        description="Authorized dealership board, business premises visit photos, or GST registration confirmation",
        required=False,
    ),
    EvidenceCategory(
        key="rc_evidence",
        title="Vehicle Registration Certificate & Hypothecation Proof",
        description="RC book copy, Parivahan/Vahan portal screenshot, engine/chassis imprint, and insurance policy copy",
        required=False,
    ),
    EvidenceCategory(
        key="other_relevant_evidence",
        title="Other Relevant Field & Market Intelligence Evidence",
        description="Neighborhood reference interview records, business board photographs, or utility bills",
        required=False,
    ),
]

PARTICULARS_LIST = [
    ParticularItem(
        id="P1",
        section="1",
        title="Name and Address",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="applicant_kyc",
        display_order=1,
        description="Full legal name, father's name, present residential address, and permanent address.",
    ),
    ParticularItem(
        id="P2",
        section="2",
        title="Residence",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="residence_evidence",
        display_order=2,
        description="Physical verification of residential premises, occupancy confirmation, and Aadhaar linkage.",
    ),
    ParticularItem(
        id="P2A",
        section="2",
        title="Whether address of residence/unit is seen and confirmed through physical visit - Observations",
        parent_id="P2",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="narrative",
        required=True,
        narrative_allowed=True,
        evidence_category="residence_evidence",
        display_order=3,
        description="Confirmation of physical visit with field observations on locality, living standard, and stability.",
    ),
    ParticularItem(
        id="P2B",
        section="2",
        title="Name of official/person who visited - Date of visit",
        parent_id="P2",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="residence_evidence",
        display_order=4,
        description="Name, employee code, and designation of visiting officer along with date and time of visit.",
    ),
    ParticularItem(
        id="P2C",
        section="2",
        title="If no, reason for not physically visiting",
        parent_id="P2",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="narrative",
        required=False,
        narrative_allowed=True,
        evidence_category=None,
        display_order=5,
        description="Specific reason / exemption justification if physical site visit could not be performed.",
    ),
    ParticularItem(
        id="P2D",
        section="2",
        title="Status of residence",
        parent_id="P2",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=True,
        narrative_allowed=False,
        evidence_category="residence_evidence",
        display_order=6,
        description="Tenure status: Owned / Parental / Ancestral / Rented / Company Provided / Leased.",
    ),
    ParticularItem(
        id="P2E",
        section="2",
        title="Aadhaar No.",
        parent_id="P2",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=True,
        narrative_allowed=False,
        evidence_category="government_verification",
        display_order=7,
        description="Masked Aadhaar number (last 4 digits visible) verified against residential identity records.",
    ),
    ParticularItem(
        id="P3",
        section="3",
        title="KYC Document Re-verification",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="government_verification",
        display_order=8,
        description="Officially valid KYC documents: Aadhaar Card, PAN Card, DL No., and Government portal verification status/details.",
    ),
    ParticularItem(
        id="P4",
        section="4",
        title="Income",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="income_documents",
        display_order=9,
        description="Substantiation of borrower and guarantor income, employment stability, and document genuineness.",
    ),
    ParticularItem(
        id="P4A",
        section="4",
        title="Documents seen",
        parent_id="P4",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=True,
        narrative_allowed=False,
        evidence_category="income_documents",
        display_order=10,
        description="List of verified income proofs: Salary Slips, Form 16, ITR acknowledgments, Financial Statements.",
    ),
    ParticularItem(
        id="P4B",
        section="4",
        title="Pertains to year - Remarks on genuineness",
        parent_id="P4",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="narrative",
        required=True,
        narrative_allowed=True,
        evidence_category="income_documents",
        display_order=11,
        description="Assessment years / periods covered and findings regarding genuineness, tax filing regularity, or employer consistency.",
    ),
    ParticularItem(
        id="P4C",
        section="4",
        title="If salaried, employer name and address",
        parent_id="P4",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=False,
        narrative_allowed=False,
        evidence_category="income_documents",
        display_order=12,
        description="Official employer / organization name, corporate office address, and contact coordinates.",
    ),
    ParticularItem(
        id="P4D",
        section="4",
        title="Designation / Occupation - Income details - Years in occupation",
        parent_id="P4",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="income_documents",
        display_order=13,
        description="Professional role, net monthly / annual gross income, and total continuous experience in current occupation.",
    ),
    ParticularItem(
        id="P5",
        section="5",
        title="Bank Statement",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="bank_documents",
        display_order=14,
        description="Re-verification of operative bank accounts, salary/business credits, and banking conduct.",
    ),
    ParticularItem(
        id="P5A",
        section="5",
        title="Bank & Branch",
        parent_id="P5",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=True,
        narrative_allowed=False,
        evidence_category="bank_documents",
        display_order=15,
        description="Name of the banking institution and specific branch maintaining the primary operative account.",
    ),
    ParticularItem(
        id="P5B",
        section="5",
        title="Type of Account",
        parent_id="P5",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="text",
        required=True,
        narrative_allowed=False,
        evidence_category="bank_documents",
        display_order=16,
        description="Account classification: Savings Bank / Current Account / Overdraft / Cash Credit.",
    ),
    ParticularItem(
        id="P5C",
        section="5",
        title="Statement examined from/to",
        parent_id="P5",
        applicant_supported=True,
        guarantor_supported=True,
        data_type="composite",
        required=True,
        narrative_allowed=False,
        evidence_category="bank_documents",
        display_order=17,
        description="Start and end dates of the examined banking period (minimum 6 months) and key turnover observations.",
    ),
    ParticularItem(
        id="P6",
        section="6",
        title="Remarks on Track Record / Criminal Antecedents",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="narrative",
        required=True,
        narrative_allowed=True,
        evidence_category="other_relevant_evidence",
        display_order=18,
        description="Market feedback, local credit reputation, track record, and adverse legal/criminal database check findings.",
    ),
    ParticularItem(
        id="P7",
        section="7",
        title="Dealer & Invoice/RC Book Verification for Vehicles/Machineries",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=False,
        data_type="composite",
        required=False,
        narrative_allowed=False,
        evidence_category="vehicle_invoice",
        display_order=19,
        description="Collateral and asset verification for vehicle, equipment, or machinery loan applications.",
    ),
    ParticularItem(
        id="P7A",
        section="7",
        title="For New Vehicles/Machineries",
        parent_id="P7",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="composite",
        required=False,
        narrative_allowed=False,
        evidence_category="vehicle_invoice",
        display_order=20,
        description="Verification details for brand new showroom vehicle or machinery procurement.",
    ),
    ParticularItem(
        id="P7A1",
        section="7",
        title="Dealer/Sub-dealer name/address",
        parent_id="P7A",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="text",
        required=False,
        narrative_allowed=False,
        evidence_category="dealer_evidence",
        display_order=21,
        description="Name, address, and authorization status of supplying dealer or original equipment manufacturer.",
    ),
    ParticularItem(
        id="P7A2",
        section="7",
        title="Genuineness of Invoice/Advance Payment Receipts",
        parent_id="P7A",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="narrative",
        required=False,
        narrative_allowed=True,
        evidence_category="vehicle_invoice",
        display_order=22,
        description="Physical confirmation of invoice genuineness, quotation parity, and borrower advance margin money deposit.",
    ),
    ParticularItem(
        id="P7B",
        section="7",
        title="For Old/Used Vehicles/Machineries",
        parent_id="P7",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="composite",
        required=False,
        narrative_allowed=False,
        evidence_category="rc_evidence",
        display_order=23,
        description="Verification details for pre-owned or secondary market vehicles and machineries.",
    ),
    ParticularItem(
        id="P7B1",
        section="7",
        title="Correctness of RC Book No./Machinery No.",
        parent_id="P7B",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="text",
        required=False,
        narrative_allowed=False,
        evidence_category="rc_evidence",
        display_order=24,
        description="Physical verification of Registration Certificate (RC), engine number, and chassis serial number against VAHAN.",
    ),
    ParticularItem(
        id="P7B2",
        section="7",
        title="Charge noted details in RC",
        parent_id="P7B",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="text",
        required=False,
        narrative_allowed=False,
        evidence_category="rc_evidence",
        display_order=25,
        description="Existing hypothecation or charge endorsement details recorded in RC book / RTO records.",
    ),
    ParticularItem(
        id="P7B3",
        section="7",
        title="Insurance details & validity",
        parent_id="P7B",
        applicant_supported=True,
        guarantor_supported=False,
        data_type="composite",
        required=False,
        narrative_allowed=False,
        evidence_category="rc_evidence",
        display_order=26,
        description="Insurance company name, policy number, coverage type (Comprehensive/Third Party), and validity expiry date.",
    ),
    ParticularItem(
        id="P8",
        section="8",
        title="General Information / Opinion",
        parent_id=None,
        applicant_supported=True,
        guarantor_supported=True,
        data_type="narrative",
        required=True,
        narrative_allowed=True,
        evidence_category="other_relevant_evidence",
        display_order=27,
        description="Holistic field officer assessment and synthesis of borrower suitability, integrity, and creditworthiness.",
    ),
]

TEMPLATE_V1_0 = ReportTemplate(
    template_key="standard_reverification",
    template_version="v1.0",
    name="Standard Background Information & Re-Verification Report",
    description="Machine-readable versioned template modeled on the standard banking pre-sanction re-verification report format.",
    header=HEADER_CONFIG,
    particulars=PARTICULARS_LIST,
    footer=FOOTER_CONFIG,
    evidence_categories=EVIDENCE_CATEGORIES,
)
