"""
PDF Report Generation Service
Generates a professional Enterprise Verification Report V6.
"""
import logging, os, json
from datetime import datetime
from typing import Dict, Any, List
from sqlalchemy.orm import Session

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, Image, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

from app.core.config import settings
from app.models.application import Application
from app.models.verification_report import VerificationReport

logger = logging.getLogger(__name__)

def _mask(value: str, show: int = 4) -> str:
    if not value or value == "N/A":
        return "N/A"
    if len(value) <= show:
        return value
    return "*" * (len(value) - show) + value[-show:]

def generate_report(application_id: int, db: Session) -> str:
    """Generate a comprehensive Enterprise Verification PDF report V6."""
    os.makedirs(settings.REPORT_DIR, exist_ok=True)
    report_gen_dt = datetime.utcnow()
    filename = f"report_{application_id}_{report_gen_dt.strftime('%Y%m%d%H%M%S')}.pdf"
    filepath = os.path.join(settings.REPORT_DIR, filename)

    app = db.query(Application).filter(Application.id == application_id).first()
    if not app:
        raise ValueError(f"Application {application_id} not found.")

    report = db.query(VerificationReport).filter(VerificationReport.application_id == application_id).first()
    
    def safe_json(val):
        if isinstance(val, dict): return val
        if isinstance(val, list): return val
        if isinstance(val, str):
            try: return json.loads(val)
            except: return {}
        return {}

    extracted = safe_json(report.extracted_info) if report else {}
    verification_details = safe_json(report.verification_details) if report else {}
    fraud = safe_json(report.fraud_analysis) if report else {}
    agent_trace = safe_json(report.agent_trace) if report else {}

    branch_val = app.branch or "Head Office"
    app_id_val = f"APP-{app.id:06d}"
    loan_num_val = f"LN-{report_gen_dt.strftime('%Y%m')}-{app.id:04d}"
    gen_date_val = report_gen_dt.strftime('%d %b %Y, %H:%M')
    officer_val = app.user.name if app.user else "System Automated"

    def draw_header_footer(canvas, doc):
        canvas.saveState()
        
        # Watermark (light diagonal)
        canvas.setFillColor(colors.HexColor("#cbd5e1"))
        canvas.setFont("Helvetica-Bold", 80)
        canvas.setFillAlpha(0.07)
        canvas.translate(A4[0]/2, A4[1]/2)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "CONFIDENTIAL")
        canvas.rotate(-45)
        canvas.translate(-A4[0]/2, -A4[1]/2)
        canvas.setFillAlpha(1)
        
        # Header Box Placeholder for Logo
        canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
        canvas.rect(40, A4[1] - 80, 80, 50, fill=0)
        canvas.setFont("Helvetica-Oblique", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(80, A4[1] - 55, "LOGO")

        canvas.setFillColor(colors.HexColor("#1e3a8a"))
        canvas.setFont("Helvetica-Bold", 16)
        canvas.drawCentredString(A4[0] / 2.0, A4[1] - 40, "SMARTVERIFY")
        
        canvas.setFont("Helvetica", 10)
        canvas.setFillColor(colors.HexColor("#475569"))
        canvas.drawCentredString(A4[0] / 2.0, A4[1] - 55, "AI Assisted Loan Verification System")
        
        canvas.setFont("Helvetica-Bold", 12)
        canvas.setFillColor(colors.HexColor("#0f172a"))
        canvas.drawCentredString(A4[0] / 2.0, A4[1] - 75, "ENTERPRISE LOAN VERIFICATION REPORT")
        
        # Header Info Grid
        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(colors.HexColor("#334155"))
        
        canvas.drawString(45, A4[1] - 105, f"Branch: {branch_val}")
        canvas.drawString(45, A4[1] - 117, f"Application No: {app_id_val}")
        canvas.drawString(45, A4[1] - 129, f"Loan No: {loan_num_val}")
        
        canvas.drawRightString(A4[0] - 45, A4[1] - 105, f"Verification Date: {report_gen_dt.strftime('%d %b %Y')}")
        canvas.drawRightString(A4[0] - 45, A4[1] - 117, f"Generated Time: {gen_date_val}")
        canvas.drawRightString(A4[0] - 45, A4[1] - 129, f"Officer Name: {officer_val}")
        
        canvas.setStrokeColor(colors.HexColor("#94a3b8"))
        canvas.setLineWidth(1.5)
        canvas.line(40, A4[1] - 140, A4[0] - 40, A4[1] - 140)
        
        # Footer
        canvas.setLineWidth(1.0)
        canvas.line(40, 50, A4[0] - 40, 50)
        
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(45, 35, "Generated by SMARTVERIFY - AI Assisted Loan Verification System")
        canvas.drawRightString(A4[0] - 45, 35, f"Page {doc.page}")
        
        canvas.setFont("Helvetica-BoldOblique", 8)
        canvas.drawCentredString(A4[0] / 2.0, 20, "Confidential Internal Banking Document")
        
        canvas.restoreState()

    # Document setup
    doc = BaseDocTemplate(filepath, pagesize=A4, leftMargin=1.5*cm, rightMargin=1.5*cm, topMargin=4.5*cm, bottomMargin=2.5*cm)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='normal')
    template = PageTemplate(id='AllPages', frames=frame, onPage=draw_header_footer)
    doc.addPageTemplates([template])

    styles = getSampleStyleSheet()
    normal = styles["Normal"]
    normal.leading = 14
    normal.fontSize = 10
    normal.textColor = colors.HexColor("#1e293b")
    
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=16, textColor=colors.HexColor("#1e3a8a"), fontName="Helvetica-Bold", spaceBefore=20, spaceAfter=15)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, textColor=colors.HexColor("#334155"), fontName="Helvetica-Bold", spaceBefore=15, spaceAfter=8)
    narrative = ParagraphStyle("Narrative", parent=normal, spaceBefore=8, spaceAfter=8, alignment=TA_LEFT)

    def kv_table(data_list):
        t = Table(data_list, colWidths=["35%", "65%"])
        t.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#0f172a")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        return t

    story = []

    def safe_str(val, default="N/A"):
        """Convert any value to a non-None string for use in Paragraph()."""
        if val is None:
            return default
        return str(val)


    # =========================================================================
    # Page 1: Executive Summary & Dashboard
    # =========================================================================
    overall_conf = agent_trace.get("overall_ai_confidence", "N/A")
    risk_score = report.risk_score if report else 0
    rec = (report.status or "pending").upper() if report else "PENDING"
    
    if risk_score < 40: risk_level = "LOW RISK"
    elif risk_score < 70: risk_level = "MEDIUM RISK"
    else: risk_level = "HIGH RISK"

    gov_ver_model = app.gov_verification
    if gov_ver_model:
        if gov_ver_model.aadhaar_validity_status == "Valid" and gov_ver_model.pan_aadhaar_link_status == "Linked":
            gov_status = "Successful"
        else:
            gov_status = "Review Required"
    else:
        fraud_gov = fraud.get("government_verification") or {}
        gov_status = fraud_gov.get("verification_status", "Pending")

    app_name = extracted.get("applicant_name") or app.applicant_name or "N/A"
    loan_amt = f"Rs. {app.loan_amount:,.2f}" if app.loan_amount else "N/A"

    story.append(Paragraph("EXECUTIVE SUMMARY", h1))
    
    # Recommendation Badge
    badge_color = colors.HexColor("#ef4444") if rec == "REJECTED" else                   colors.HexColor("#f59e0b") if rec in ["MANUAL REVIEW", "HIGH RISK"] else                   colors.HexColor("#10b981") if "APPROVED" in rec else                   colors.HexColor("#64748b")
                  
    badge_style = ParagraphStyle("Badge", parent=normal, fontSize=14, fontName="Helvetica-Bold", textColor=colors.white, alignment=TA_CENTER)
    t_badge = Table([[Paragraph(rec, badge_style)]], colWidths=["100%"])
    t_badge.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), badge_color),
        ("PADDING", (0, 0), (-1, -1), 12),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
    ]))
    story.append(t_badge)
    story.append(Spacer(1, 15))

    # Narrative Executive Summary
    if rec == "APPROVED":
        exec_narrative = f"The application for {app_name} requesting a loan of {loan_amt} has been comprehensively analyzed by the SMARTVERIFY AI framework. Document verification, government portal checks, and multi-agent fraud analysis have returned positive results. With an overall AI confidence of {overall_conf}% and a {risk_level} assessment, the application is clear for processing."
    else:
        exec_narrative = f"The application for {app_name} requesting a loan of {loan_amt} has undergone SMARTVERIFY analysis. The system returned a {risk_level} assessment with an overall AI confidence of {overall_conf}%. Due to discrepancies identified in the verification checks, manual review by a Credit Officer is required before proceeding."
    story.append(Paragraph(exec_narrative, narrative))
    story.append(Spacer(1, 15))

    # Executive Dashboard (Status Cards)
    story.append(Paragraph("Executive Dashboard", h2))
    dash_data = [
        ["Application Status", app.status.value.upper() if app.status else "PENDING"],
        ["Government Verification", gov_status],
        ["Rule Engine Status", "EVALUATED"],
        ["CrewAI Status", "COMPLETED" if report else "PENDING"],
        ["Fraud Risk", risk_level],
        ["Overall AI Confidence", f"{overall_conf}%"]
    ]
    story.append(kv_table(dash_data))
    
    # =========================================================================
    # Page 2: Verification Timeline & AI Confidence Breakdown
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("VERIFICATION TIMELINE", h1))
    
    tl_data = [
        ["Application Created", str(app.created_at.strftime('%Y-%m-%d %H:%M:%S')) if app.created_at else "N/A"],
        ["Documents Uploaded", str(app.created_at.strftime('%Y-%m-%d %H:%M:%S')) if app.created_at else "N/A"],
        ["OCR Completed", "Completed"],
        ["NLP Extraction Completed", "Completed"],
        ["UIDAI Verification", gov_ver_model.timestamp if gov_ver_model else "Completed"],
        ["PAN–Aadhaar Verification", gov_ver_model.timestamp if gov_ver_model else "Completed"],
        ["Rule Engine Verification", "Completed"],
        ["CrewAI Multi-Agent Analysis", str(report.created_at.strftime('%Y-%m-%d %H:%M:%S')) if report else "N/A"],
        ["Final Report Generated", gen_date_val]
    ]
    t_tl = Table(tl_data, colWidths=["60%", "40%"])
    t_tl.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t_tl)
    story.append(Spacer(1, 20))

    story.append(Paragraph("AI CONFIDENCE BREAKDOWN", h1))
    findings = agent_trace.get("agent_findings", {})
    da = findings.get("document_analyst", {})
    es = findings.get("extraction_specialist", {})
    ga = findings.get("gov_verification_agent", {})
    
    conf_data = [
        ["OCR Confidence", f"{da.get('ocr_confidence', 'N/A')}%"],
        ["NLP Confidence", f"{es.get('extraction_confidence', 'N/A')}%"],
        ["Government Verification Confidence", "100% (Direct Portal)"],
        ["Rule Engine Confidence", "100% (Deterministic)"],
        ["CrewAI Confidence", f"{ga.get('fraud_confidence', 'N/A')}%"],
        ["Overall AI Confidence", f"{overall_conf}%"],
    ]
    story.append(kv_table(conf_data))

    # =========================================================================
    # Page 3: Applicant Profile
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("APPLICANT PROFILE", h1))
    
    story.append(Paragraph("Applicant Details", h2))
    app_data = [
        ["Full Name", app_name],
        ["Date of Birth", (extracted.get("dob") or "N/A")],
        ["Gender", (extracted.get("gender") or "N/A")],
    ]
    story.append(kv_table(app_data))

    story.append(Paragraph("KYC Summary", h2))
    kyc_data = [
        ["Aadhaar Number", _mask((extracted.get("aadhaar_number") or "N/A"))],
        ["PAN Number", _mask((extracted.get("pan_number") or "N/A"))],
    ]
    story.append(kv_table(kyc_data))

    story.append(Paragraph("Income Summary", h2))
    inc_data = [
        ["Declared Monthly Income", f"Rs. {extracted.get('monthly_income', 'N/A')}"],
    ]
    story.append(kv_table(inc_data))

    story.append(Paragraph("Employment", h2))
    emp_data = [
        ["Employer Name", (extracted.get("employer_name") or "N/A")],
    ]
    story.append(kv_table(emp_data))

    story.append(Paragraph("Contact Details", h2))
    con_data = [
        ["Mobile Number", extracted.get("phone") or "N/A"],
        ["Current Address", Paragraph(extracted.get("address") or "N/A", normal)],
    ]
    story.append(kv_table(con_data))
    
    story.append(Paragraph("Applicant Photograph", h2))
    ph_data = [[Paragraph("<font color='#94a3b8'><i>[Applicant Photograph Placeholder]</i></font>", ParagraphStyle("C", alignment=TA_CENTER))]]
    t_ph = Table(ph_data, colWidths=["100%"], rowHeights=[100])
    t_ph.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc"))
    ]))
    story.append(t_ph)

    # =========================================================================
    # Page 4: Government Verification
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("GOVERNMENT VERIFICATION", h1))

    story.append(Paragraph("UIDAI Aadhaar Verification", h2))
    uidai_res = gov_ver_model.aadhaar_validity_status if gov_ver_model else fraud.get("government_verification", {}).get("aadhaar_validity_status", "Pending")
    uidai_ts = gov_ver_model.timestamp if gov_ver_model else "N/A"
    uidai_rmk = gov_ver_model.remarks if gov_ver_model else "N/A"
    uidai_data = [
        ["Portal Used", "UIDAI (myaadhaar.uidai.gov.in)"],
        ["Verification Date", uidai_ts],
        ["Verification Time", uidai_ts],
        ["Verification Result", uidai_res],
        ["Screenshot Area", "See Evidence Appendix"],
        ["Officer Observation", "Aadhaar verified successfully via UIDAI portal." if uidai_res == "Valid" else "Aadhaar verification failed or pending."],
        ["Officer Remarks", Paragraph(safe_str(uidai_rmk), normal)],
    ]
    story.append(kv_table(uidai_data))
    
    story.append(Paragraph("PAN–Aadhaar Link Verification", h2))
    pan_res = gov_ver_model.pan_aadhaar_link_status if gov_ver_model else fraud.get("government_verification", {}).get("pan_aadhaar_link_status", "Pending")
    pan_data = [
        ["Portal Used", "Income Tax e-Filing Portal"],
        ["Verification Date", uidai_ts],
        ["Verification Time", uidai_ts],
        ["Verification Result", pan_res],
        ["Screenshot Area", "See Evidence Appendix"],
        ["Officer Observation", "PAN is successfully linked to Aadhaar." if pan_res == "Linked" else "PAN-Aadhaar linkage verification failed."],
        ["Officer Remarks", Paragraph(safe_str(uidai_rmk), normal)],
    ]
    story.append(kv_table(pan_data))

    # =========================================================================
    # Page 5: Document Verification
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("DOCUMENT VERIFICATION", h1))
    
    story.append(Paragraph("OCR Findings", h2))
    ocr_obs = f"The OCR engine processed {len(app.documents) if app.documents else 0} documents successfully with a high average confidence of {da.get('ocr_confidence', 'N/A')}%. Text extraction was clean without signs of severe pixelation or unreadable artifacts."
    story.append(Paragraph(ocr_obs, narrative))
    
    story.append(Paragraph("NLP Findings", h2))
    missing = es.get("missing_fields", [])
    if missing:
        nlp_obs = f"The Natural Language Processing engine extracted entities but identified missing mandatory fields: {', '.join(missing)}."
    else:
        nlp_obs = "The Natural Language Processing engine successfully extracted all required applicant entities. No mandatory fields are missing."
    story.append(Paragraph(nlp_obs, narrative))

    # =========================================================================
    # Page 6: Loan & Property Assessment
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("LOAN & PROPERTY ASSESSMENT", h1))
    
    story.append(Paragraph("Loan Details", h2))
    ld_data = [
        ["Loan Amount", loan_amt],
        ["Loan Tenure", f"{app.loan_tenure} Months" if app.loan_tenure else "N/A"],
        ["Repayment Details", f"Proposed Interest Rate: {app.interest_rate}%" if app.interest_rate else "N/A"],
    ]
    story.append(kv_table(ld_data))
    
    story.append(Paragraph("Property Details & Valuation", h2))
    pd = app.property_details
    if pd:
        prop_data = [
            ["Property Type", pd.property_type or "N/A"],
            ["Property Address", Paragraph(safe_str(f"{pd.address or ''}, {pd.village_city or ''}"), normal)],
            ["Property Valuation", f"Market Value: Rs. {pd.market_value:,.2f}" if pd.market_value else "N/A"],
        ]
        story.append(kv_table(prop_data))
    else:
        story.append(Paragraph("No property pledged (Non-LAP Loan).", narrative))

    story.append(Paragraph("Loan Eligibility", h2))
    story.append(Paragraph("Based on the rule engine evaluation against established FOIR and LTV banking policies, the applicant meets the preliminary eligibility criteria.", narrative))
    
    story.append(Paragraph("Officer Observation", h2))
    story.append(Paragraph("The requested loan amount aligns with the property valuation and the applicant's declared income. The security cover is deemed adequate.", narrative))

    # =========================================================================
    # Page 7: Site Verification
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("SITE VERIFICATION", h1))
    sv = app.site_verification
    if sv:
        story.append(Paragraph("Site Condition & Neighbourhood", h2))
        story.append(Paragraph(f"Inspecting officer {sv.officer_name or 'N/A'} visited the site on {sv.date or 'N/A'}. The property condition is reported as '{sv.property_condition or 'N/A'}'. The property boundary is '{sv.boundary_present or 'N/A'}'.", narrative))
        
        story.append(Paragraph("Property Access", h2))
        story.append(Paragraph(f"Road access to the property is confirmed as '{sv.road_access or 'N/A'}'.", narrative))
        
        story.append(Paragraph("Occupancy & Stage", h2))
        story.append(Paragraph("The property is confirmed to be occupied/accessible as per the captured GPS coordinates.", narrative))
        
        story.append(Paragraph("Officer Remarks", h2))
        story.append(Paragraph(sv.remarks or "No additional remarks.", narrative))
    else:
        story.append(Paragraph("Site verification is pending or not applicable for this loan type.", narrative))

    # =========================================================================
    # Page 8: CrewAI Investigation
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("CREWAI INVESTIGATION", h1))
    
    for agent_name, payload in findings.items():
        clean_name = agent_name.replace("_", " ").title()
        explain = payload.get("explainability", {})
        story.append(Paragraph(f"{clean_name}", h2))
        agent_data = [
            ["Objective", "Assess specific compliance, extraction, or fraud metrics."],
            ["Input Received", "Application dossier and system extracted data."],
            ["Tools Used", Paragraph(safe_str(", ".join(explain.get("tools_invoked", ["Internal Evaluator"]))), normal)],
            ["Reasoning", Paragraph(safe_str(explain.get("reasoning"), "Evaluated based on banking policies."), normal)],
            ["Evidence Used", Paragraph(safe_str(", ".join(explain.get("evidence_used", ["Applicant Data"]))), normal)],
            ["Confidence", f"{explain.get('confidence', 'High')}%"],
            ["Decision", Paragraph(safe_str(explain.get("decision"), "Proceed"), normal)]
        ]
        story.append(kv_table(agent_data))

    # =========================================================================
    # Page 9: Fraud Investigation
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("FRAUD INVESTIGATION", h1))
    
    fraud_issues = ga.get("issues", [])
    fraud_flags = {
        "Duplicate PAN": "NO",
        "Duplicate Aadhaar": "NO",
        "Government Verification Mismatch": "YES" if ga.get("fraud_flag") else "NO",
        "OCR Tampering": "YES" if any("tamper" in i.lower() for i in fraud_issues) else "NO",
        "Document Forgery": "YES" if any("forger" in i.lower() for i in fraud_issues) else "NO",
        "Historical Similarity": "NO",
    }
    
    story.append(Paragraph("Fraud Indicators", h2))
    indicator_data = [[k, v] for k, v in fraud_flags.items()]
    story.append(kv_table(indicator_data))
    
    story.append(Paragraph("Risk Summary", h2))
    story.append(Paragraph(f"The overarching fraud risk score generated is {ga.get('fraud_score', ga.get('fraud_confidence', 'N/A'))}/100. The risk level is {risk_level}.", narrative))
    
    story.append(Paragraph("Narrative Analysis", h2))
    story.append(Paragraph("The multi-agent system performed cross-checks against systemic historical databases and government portals. The document integrity is intact with no signs of digital forgery or pixel tampering detected in the submitted identity cards.", narrative))
    
    story.append(Paragraph("Final Fraud Conclusion", h2))
    story.append(Paragraph("MANUAL REVIEW REQUIRED" if ga.get("fraud_flag") else "PROCEED - No Fraud Detected", narrative))

    # =========================================================================
    # Page 10: Final Recommendation
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("FINAL RECOMMENDATION", h1))
    
    story.append(Paragraph("General Opinion", h2))
    if rec == "APPROVED":
        opinion = "Based on the physical verification, government verification, document validation and AI-assisted analysis, the applicant appears completely eligible for the requested loan. No significant discrepancies were identified across the risk vectors."
    else:
        opinion = "Based on the physical verification, government verification, document validation and AI-assisted analysis, the applicant presents certain risk factors that require manual oversight. The automated system recommends manual review."
    story.append(Paragraph(opinion, narrative))
    
    story.append(Spacer(1, 15))
    story.append(t_badge) # Re-use the large colored badge
    story.append(Spacer(1, 15))
    
    rec_data = [
        ["AI Confidence", f"{overall_conf}%"],
        ["Risk Level", risk_level],
        ["Fraud Score", str(ga.get("fraud_score", ga.get("fraud_confidence", "N/A")))],
        ["Verification Score", f"{report.verification_score if report else 0.0:.1f} / 100"],
        ["AI Reasoning", Paragraph(safe_str(agent_trace.get("recommendation")), normal)],
        ["Executive Synopsis", Paragraph(safe_str(agent_trace.get("summary") or getattr(report, "agent_summary", None)), normal)],
        ["Officer Observation", Paragraph(safe_str(agent_trace.get("human_review"), "Awaiting final sign-off."), normal)],
    ]
    story.append(kv_table(rec_data))

    # =========================================================================
    # Page 11+: Evidence Appendix
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("EVIDENCE APPENDIX", h1))
    
    def render_evidence_block(title):
        img_box = [[Paragraph("<font color='#94a3b8'><i>[Image Area]</i></font>", ParagraphStyle("C", alignment=TA_CENTER))]]
        t_img = Table(img_box, colWidths=["100%"], rowHeights=[120])
        t_img.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc"))
        ]))
        
        ev_meta_data = [
            ["Evidence Type", title],
            ["Captured Date", gen_date_val],
            ["Captured Time", gen_date_val],
            ["Captured By", "System Extracted"],
            ["Observation", "Visual integrity confirmed."]
        ]
        
        return KeepTogether([t_img, Spacer(1, 5), kv_table(ev_meta_data), Spacer(1, 20)])
        
    evidence_types = [
        "Applicant Photograph", "UIDAI Screenshot", "PAN Screenshot", 
        "Property Photograph", "Property Interior", "Property Exterior", 
        "Site Images", "Dealer Images", "Quotation Images", "GST Screenshot"
    ]
    for ev in evidence_types:
        story.append(render_evidence_block(ev))

    # =========================================================================
    # Last Page: Approvals & Metadata
    # =========================================================================
    story.append(PageBreak())
    story.append(Paragraph("APPROVALS", h1))
    story.append(Spacer(1, 20))
    
    sig_data = [
        ["Prepared By", "Verified By", "Approved By"],
        ["", "", ""],
        ["[ Digital Signature ]", "[ Digital Signature ]", "[ Digital Signature ]"],
        [officer_val, "Senior Officer", "Branch Manager"],
        [f"Date: {report_gen_dt.strftime('%d %b %Y')}", "Date: ________________", "Date: ________________"],
        ["Remarks:", "Remarks:", "Remarks:"]
    ]
    sig_table = Table(sig_data, colWidths=["33%", "33%", "34%"], rowHeights=[20, 60, 20, 20, 20, 20])
    sig_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("VALIGN", (0, 5), (-1, 5), "TOP"),
        ("ALIGN", (0, 5), (-1, 5), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#94a3b8")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(sig_table)
    story.append(Spacer(1, 30))
    
    story.append(Paragraph("REPORT METADATA", h2))
    
    rpt_meta_left = [
        ["SMARTVERIFY Version", "6.0.0 (Enterprise Build)"],
        ["Gemini Model Used", "Gemini 1.5 Pro"],
        ["CrewAI Version", "0.22.x"],
        ["Generated By", officer_val],
        ["Generated On", gen_date_val],
        ["Report ID", f"REP-{report_gen_dt.strftime('%Y%m%d%H%M%S')}-{app.id}"],
        ["Verification ID", f"VER-{report.id if report else 'PENDING'}"],
        ["Application ID", app_id_val],
    ]
    t_meta_left = Table(rpt_meta_left, colWidths=["50%", "50%"])
    t_meta_left.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    
    qr_box = [[Paragraph("<font color='#94a3b8'>[ QR CODE PLACEHOLDER ]</font>", ParagraphStyle("C", alignment=TA_CENTER))]]
    t_qr = Table(qr_box, colWidths=["100%"], rowHeights=[150])
    t_qr.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
    ]))
    
    meta_outer = [[t_meta_left, t_qr]]
    t_meta_outer = Table(meta_outer, colWidths=["65%", "35%"])
    t_meta_outer.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
    ]))
    story.append(t_meta_outer)
    
    # =========================================================================
    # Build Document
    # =========================================================================
    doc.build(story)
    
    logger.info(f"PDF report saved: {filepath}")
    return filepath
