"""
SmartVerify - Autonomous AI System for Intelligent Loan Verification
Main FastAPI Application Entry Point
"""
import logging, os
from pathlib import Path
from fastapi import FastAPI, Request
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.core.config import settings
from app.core.logging_config import setup_logging
from app.api.endpoints import auth, documents, verification, applications, dashboard, reports
from app.db.database import engine, Base

setup_logging()
logger = logging.getLogger(__name__)

# Create all tables only for SQLite local development; PostgreSQL schema is managed by Alembic
if settings.DATABASE_URL.startswith("sqlite"):
    Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="SmartVerify API",
    description="Autonomous AI System for Intelligent Loan Verification",
    version="1.0.0",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_origin_regex=r"https?://.*",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
os.makedirs(settings.REPORT_DIR, exist_ok=True)
app.mount("/uploads", StaticFiles(directory=settings.UPLOAD_DIR), name="uploads")
app.mount("/reports", StaticFiles(directory=settings.REPORT_DIR), name="reports")

# API Routers
app.include_router(auth.router,         prefix="/auth",         tags=["Authentication"])
app.include_router(documents.router,    prefix="/documents",    tags=["Documents"])
app.include_router(verification.router, prefix="/verify",       tags=["Verification"])
app.include_router(applications.router, prefix="/applications", tags=["Applications"])
app.include_router(dashboard.router,    prefix="/dashboard",    tags=["Dashboard"])
app.include_router(reports.router,      prefix="/report",       tags=["Reports"])
app.include_router(reports.router,      prefix="/api/reports",  tags=["Reports"])


@app.get("/health", tags=["Health"])
async def health_check():
    return {"status": "healthy"}


# ── Frontend SPA Integration ──────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_BUILD_DIR = Path(
    os.getenv("FRONTEND_BUILD_DIR", str(BASE_DIR.parent / "frontend" / "build"))
)

if FRONTEND_BUILD_DIR.is_dir() and (FRONTEND_BUILD_DIR / "index.html").is_file():
    logger.info("Serving frontend SPA from %s", FRONTEND_BUILD_DIR)

    # Mount static assets (CSS, JS, media generated by CRA)
    frontend_static = FRONTEND_BUILD_DIR / "static"
    if frontend_static.is_dir():
        app.mount("/static", StaticFiles(directory=str(frontend_static)), name="frontend_static")

    @app.middleware("http")
    async def spa_middleware(request: Request, call_next):
        path = request.url.path

        # Preserve backend API, documentation, static uploads/reports, and file downloads
        is_api_or_system = (
            path.startswith("/api/")
            or path.startswith("/openapi.json")
            or path.startswith("/docs")
            or path.startswith("/redoc")
            or path == "/health"
            or path.startswith("/uploads/")
            or path.startswith("/reports/")
            or path.startswith("/static/")
            or path.endswith("/download")
        )

        # If a browser is requesting a page directly (Accept header includes text/html),
        # return index.html for client-side routing, avoiding JSON/401 API responses
        if request.method in ("GET", "HEAD") and not is_api_or_system:
            accept = request.headers.get("accept", "")
            if "text/html" in accept:
                file_target = FRONTEND_BUILD_DIR / path.lstrip("/")
                if file_target.is_file() and path != "/":
                    return FileResponse(str(file_target))
                return FileResponse(str(FRONTEND_BUILD_DIR / "index.html"))

        response = await call_next(request)

        # Fallback to index.html for unknown GET paths (client-side SPA routing)
        if response.status_code == 404 and request.method in ("GET", "HEAD") and not is_api_or_system:
            file_target = FRONTEND_BUILD_DIR / path.lstrip("/")
            if file_target.is_file():
                return FileResponse(str(file_target))
            return FileResponse(str(FRONTEND_BUILD_DIR / "index.html"))

        return response

    @app.get("/", tags=["Frontend"])
    async def root():
        return FileResponse(str(FRONTEND_BUILD_DIR / "index.html"))

    @app.get("/{full_path:path}", include_in_schema=False)
    async def spa_catch_all(full_path: str):
        file_target = FRONTEND_BUILD_DIR / full_path
        if file_target.is_file():
            return FileResponse(str(file_target))
        return FileResponse(str(FRONTEND_BUILD_DIR / "index.html"))

else:
    logger.info("No frontend build found at %s. API-only mode.", FRONTEND_BUILD_DIR)

    @app.get("/", tags=["Health"])
    async def root():
        return {"status": "ok", "service": "SmartVerify API", "version": "1.0.0"}

