// SmartVerify - Shared Constants (single source of truth)
export const BRANCHES = [
  'Agrahara GP',
  'Alur',
  'Arehalli',
  'Arkalgud',
  'Arsikere-Hoysaleshwara College Campus',
  'Arsikere-Main',
  'Attavara GP',
  'Banavara',
  'Bannur',
  'Belagodu',
  'Belur',
  'Bhugathagalli',
  'Chamarajanagar',
  'Channarayapatna',
  'Cherambane',
  'Chilkunda',
  'Dudda',
  'Gonikoppal',
  'Gundlupet',
  'Hanbal',
  'Haradanahalli GP',
  'Hassan',
  'Hassan - Vijayanagar',
  'Hassan-Kuvempunagar',
  'Hassan-Vidyanagar',
  'Heggadadevanakote',
  'Holenarasipura',
  'Hootagally',
  'Hunsur',
  'Kalenahalli GP',
  'Kesagodu GP',
  'Kodlipet',
  'Kollegala',
  'Kothegala GP',
  'Kowshika',
  'Krishnarajanagar',
  'Kudige',
  'Kushalnagar',
  'Lakkur GP',
  'Madikeri',
  'Magge',
  'Mallappanahally GP',
  'Mysuru - Rajendranagar',
  'Mysuru - Ramanuja Road',
  'Mysuru - SVP Nagara',
  'Mysuru - Vijayanagar IV Stage',
  'Mysuru-Bogadi',
  'Mysuru-Devraj Urs Road',
  'Mysuru-J P Nagar',
  'Mysuru-Kanakadasanagar',
  'Mysuru-Kuvempunagar',
  'Mysuru-Nazarbad',
  'Mysuru-Rajiv Nagar',
  'Mysuru-Sankranthi Circle, Hebbal 2nd Stage',
  'Mysuru-Saraswathipuram',
  'Mysuru-Siddarthanagar',
  'Mysuru-V.V.Mohalla',
  'Mysuru-Vijayanagar I Stage (DBU Digital Banking Unit)',
  'Mysuru-Vijayanagar II Stage',
  'Mysuru-Vivekanandanagar',
  'Nanjangud',
  'Periyapatna',
  'Rudrapatna',
  'Sakleshpur',
  'Siddalingapura',
  'Somwarpet',
  'Suntikoppa',
  'Thandre',
  'Udevara GP',
  'Virajpet',
  'Heggadadevanapura'
];

export const LOAN_TYPES = [
  'Home Loan',
  'Personal Loan',
  'Auto / Vehicle Loan',
  'Education Loan',
  'Business Loan',
  'Mortgage Loan',
  'Gold Loan',
  'Agricultural Loan',
];

export const PROPERTY_TYPES = [
  'Residential Apartment',
  'Independent House',
  'Commercial Property',
  'Agricultural Land',
  'Plot / Land',
  'Villa',
];

export const PROPERTY_CONDITIONS = [
  'Excellent',
  'Good',
  'Fair',
  'Poor',
  'Under Construction',
];
